# Numpy - Numerical Python

- Its stands for numerical python
- its a fundamental package for scientific computing with python

- Numpy is a python library used for working with arrays
- It has functions for working in domain of linear algebra, fourier transform and matrices
          - What is an aaray
               -an array is a data structure that stores valeus of same data type. In python this is the main difference between arrays and lists
              - where python lists can contain values corresponding to different data types
                     - in arrays in python can contain only values corresponding to the same data type

In [127]:
# initially lets import numpy
import numpy as np

In [128]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [129]:
type(arr)

numpy.ndarray

In [130]:
arr #this is one dimenstional array ---- because its starting from one bracket and end on on single bracket [] but in 2D array its 2 opening brackets two closing brackets

array([1, 2, 3, 4, 5])

In [131]:
arr.shape   #shape - how many no of rows and columns are in array) so here only one is given that is 5 hence its 1D array

(5,)

In [132]:
arr.reshape() # to create more dimensional array)

TypeError: reshape() takes exactly 1 argument (0 given)

In [133]:
# Multinested array
lst1 = [1,2,3,4,5]
lst2 =[2,3,4,5,6]
lst3 = [9,7,6,8,9]  # trry to convert these lists into aan array

arr = np.array([lst1,lst2,lst3])

In [134]:
arr  # Creating a multidimenstional array (3 rows,5 columns)     but in 2D array its 2 opening brackets two closing brackets thats how we check if its 1D or 2D

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [135]:
arr.shape

(3, 5)

In [136]:
arr.reshape(5,3) # always check the total ELEMENTS count of array for instance here is 15 before reshapeing and 15 aftewr reshapeing it shou;d be same for the before and after process


array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [137]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [138]:
arr.shape

(3, 5)

#### Indexing


In [139]:
# Accessing the array elements
arr=np.array([1,2,3,4,5,6,7,8,9])

In [140]:
arr[3]

4

In [141]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
lst1 = [1,2,3,4,5]
lst2 =[2,3,4,5,6]
lst3 = [9,7,6,8,9]

arr = np.array([lst1,lst2,lst3])


In [143]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

#####  Row Index and column index


array([[1, 2, 3, 4, 5], row index is zero here
       [2, 3, 4, 5, 6], row index is one here
       [9, 7, 6, 8, 9]]) row index is two here
        
        
        
        
        same goes for column Index
       # array([[1, 2, 3, 4, 5], 
                [2, 3, 4, 5, 6],
                [9, 7, 6, 8, 9]]) 
        here,---- 1,2,9 {o index column}
             ---- 2,3,7 {1 index colummn} and so on,...  
        
        
        

##### how indexing can be done in 2D

In [144]:
arr[:,:]   #left side is row and (:) right side is column

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

suppose i want  1,2
                 2,3    so here what ill do is '
    check 
    - Zeroth row' arr[0:2]  - means from 0 to 2nd index
    
    
    arr[0:2,0:2] and 0 index to 2index column 

In [145]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [146]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

pick 4,5
      6,8    and pic 3,4,5

In [155]:
arr[1:,2:4]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [152]:
arr[1,1:4]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

-----------------------

#### in-built Functions

In [153]:
arr = np.arange(0,10)

In [154]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr = np.arange(0,10, step =3)

In [55]:
arr

array([0, 3, 6, 9])

### Linspace()

The NumPy linspace function (sometimes called np. linspace) is a tool in Python for creating numeric sequences. It's somewhat similar to the NumPy arange function, in that it creates sequences of evenly spaced numbers structured as a NumPy array. There are some differences though

-linspace allows you to define how many values you get including the specified min and max value. It infers the stepsize: np. arange allows you to define the stepsize and infers the number of steps(the number of values you get).

In [57]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

#### Copy function

In [59]:

arr=np.array([1,2,3,4,5,6,7,8,9]) 

In [60]:
arr  # 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
# Copy function  and broadcasting
#for ex here i want after 3 replace all the numbers with 400

arr[3:] =400

In [69]:
arr

array([  1,   2,   3, 400, 400, 400, 400, 400, 400])

In [70]:
arr1=arr

In [71]:
arr1[3:] =500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [72]:
arr    # its called referal style, array is actually called refrence style

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [76]:
arr1 =arr.copy()

In [79]:
print(arr)
arr1[3:]=1000
print(arr1)   #copy() ----its just creating a memory space for arr for storing the values in another place

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [83]:
#Some conditions very useful in exploratoty data analysis

val =2

arr>2


array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [84]:
# you can also do this
arr*3

array([   3,    6,    9, 1500, 1500, 1500, 1500, 1500, 1500])

In [87]:
arr[arr<2] # if i want the exact values that are less than 2

array([1])

In [89]:
# Create arrays and reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [102]:
np.arange(0,20).reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [106]:
np.ones(5) #by default datatype is flot here

#its basically creates an array where every elemnet is one

array([1., 1., 1., 1., 1.])

In [108]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [111]:
# 2Dimenstional array in ones

np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Random Functions

In [116]:
# Random Distribution
np.random.rand(3,4)

array([[0.18615959, 0.84065362, 0.82520237, 0.7654502 ],
       [0.26284855, 0.95903087, 0.78951278, 0.45538084],
       [0.08968785, 0.48895728, 0.21420927, 0.02308801]])

In [117]:
arr_ex = np.random.randn(4,4)

In [118]:
arr_ex

array([[-1.15274268,  0.95947875, -1.05952791, -0.48927468],
       [ 0.81477546,  1.06677912,  0.85911728,  0.26330667],
       [ 0.97964439,  0.1797484 , -0.65074194,  0.47148683],
       [ 0.11709354,  0.90646631,  1.44320098,  1.26270475]])

In [122]:
import seaborn as sns
import pandas as pd

In [124]:
sns.distplot(pd.Dataframe(arr_ex.reshape(16,1)))

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [125]:
np.random.randint(0,100,8).reshape(4,2)  # it means select 8 numbers from 0 to 100 integers

array([[61, 33],
       [11, 63],
       [21, 74],
       [79, 56]])

In [126]:
np.random.random_sample((1,15))

array([[0.5852779 , 0.55276918, 0.25673286, 0.20476249, 0.72186472,
        0.99288048, 0.23697666, 0.85377138, 0.09702193, 0.79523052,
        0.52809528, 0.55374517, 0.72547145, 0.96626713, 0.55869612]])